# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build & test

env:
  GRADLE_OPTS: -Dkotlin.compiler.execution.strategy="in-process"

on:
  pull_request:
  push:
    branches: [ main, release/* ]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - uses: burrunan/gradle-cache-action@cbdf4342ff988d143aa7a5aeceedffafb8c74bcf #v1.10
      name: Build with Gradle
      with:
        arguments: build
        # Need to add the properties here to re-use the Gradle daemon during publishing
        properties: |
          NEXUS_USERNAME=${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD=${{ secrets.NEXUS_PASSWORD }}

    - uses: burrunan/gradle-cache-action@cbdf4342ff988d143aa7a5aeceedffafb8c74bcf #v1.10
      name: Publish Maven artifacts
      if: ${{ github.ref == 'refs/heads/main' || contains(github.ref, 'release/') }}
      with:
        arguments: publish
        properties: |
          NEXUS_USERNAME=${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD=${{ secrets.NEXUS_PASSWORD }}

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test Results Linux
        path: '**/test-results/**/*.xml'
